### ISSUE TITLE
execution in proxy environment

### ISSUE THREAD

**Issue by c5101010** [watson-developer-cloud/speech-to-text-websockets-python#12]
Hi, thank you for the script. 

It is very helpful, however, I can't execute in proxy environment.
If it would be possible, could I have some advice to modify to execute the script in proxy environment?

Thank you very much

**Comment by kognate** [comment]
What kind of proxy environment are you running in?  For example is it a Socks proxy, or some HTML proxy?  Also, you might want to read over this https://www.infoq.com/articles/Web-Sockets-Proxy-Servers which gives a pretty good overview of how WebSockets handle HTML proxy passing.

**Comment by c5101010** [comment]
Thank you for your quick reply.

My system is behind HTTP proxy (internal company proxy).

The link you provided looks very informative.
I will try to check up on that.

Best,
Kenji(c5101010)

**Comment by cclauss** [comment]
@c5101010 Can this issue be closed?
