### ISSUE TITLE
No module named cryptography

### ISSUE THREAD

**Issue by vikaskumar03** [watson-developer-cloud/speech-to-text-websockets-python#13]
I am using python 3.4.0 on windows-7(64 bit) and getting "No Module Named Cryptography" error.
I have attached the screenshot to get the detailed error.
![python](https://cloud.githubusercontent.com/assets/20227118/16491967/9ba7a868-3efd-11e6-95da-8cc4da395404.PNG)

I have also googled this error but didn't able to resolve this issue.
How can i resolve this issue?

**Comment by daniel-bolanos** [comment]
can you try $ pip install cryptography

I have this one insalled:

cryptography (1.0.1)

Dani

**Comment by cclauss** [comment]
@vikaskumar03 Is this issue still open?
