### ISSUE TITLE
Basic pep8 compliance

### ISSUE THREAD

**Issue by sdague** [watson-developer-cloud/speech-to-text-websockets-python#17]
As a sample python example program it would be really good if this followed python pep8 best practices so that it matched with other python code. For instance:

4 space indents
80 column wraps

I'm happy to make the changes and push a pull request if this is welcomed.

**Comment by daniel-bolanos** [comment]
Hi @sdague that is a ver good suggestion, I agree, it would be good to stick to the best practices. If you make a pull request I will take a look at it and merge it, thanks a lot!
