### ISSUE TITLE
Support for speaker labels?

### ISSUE THREAD

**Issue by michellemorales** [watson-developer-cloud/speech-to-text-websockets-python#19]
Thanks for the great repo! I was able to get the test example working easily. 

I was wondering if future updates will include the possibility of outputting [speaker_labels](https://www.ibm.com/watson/developercloud/doc/speech-to-text/output.html)?

**Comment by daniel-bolanos** [comment]
Hi @michellemorales thank you, I'm glad it was useful to you. I think this project has been merged, or it is about to be merged into the Watson python sdk, please check this link: https://github.com/watson-developer-cloud/python-sdk/issues/12
