### ISSUE TITLE
Possible to Get Output File (JSON) That Includes "Results"->"Alternatives"->"Timestamps", etc?

### ISSUE THREAD

**Issue by smilingkylan** [watson-developer-cloud/speech-to-text-websockets-python#2]
I know that it's in streaming mode and converting the JSON output to an enumerated result in the output TXT file, but I was wondering if there's any way to get it to output all of the accumulated JSON for the audio into a single JSON file.

Unfortunately I don't know Python so I'm not able to edit the code to modify the format of the output to JSON, but I know at the very least having the timestamps available would be useful for people trying to create subtitles and other similar features.

**Comment by daniel-bolanos** [comment]
Hi @kylanhurt , yes, I'm working on that feature, hopefully it will be ready soon, in the meantime just redirect to a file and do: " > cat file.txt | cut -f4 "

that will give you the JSON without the timestamps...

**Comment by daniel-bolanos** [comment]
done

@kylanhurt
