### ISSUE TITLE
extend this feature to general stt

### ISSUE THREAD

**Issue by surajhes** [watson-developer-cloud/speech-to-text-websockets-python#22]
Hi i wanted to understand if this script can be used in a way where it listens to the speech from the microphone of the user and performs the transcribing of the spoken test?

**Comment by daniel-bolanos** [comment]
currently it does not have an option to take audio from the microphone, however adding support for that should be quite simple, just grab the samples and feed them to the service like `maybeSendChunk` does, you just need to know the recording format in case you need to change the `content-type` value . If you decide to do it we would be very happy to incorporate it via pull request.

**Comment by aishaambar** [comment]
Hi. @daniel-bolanos ! Can you clearly explain the necessary changes that I will have to make in this code,in order to take **input from microphone instead of prerecorded audio files**? 
Please help!
Waiting for your helpful response

**Comment by aishaambar** [comment]
@surajhes ,were you able to modify this code to take input from microphone??

**Comment by philippe-gregoire** [comment]
Reading from microphone will require a Python abstraction library such as PyAudio.
Or on Linux systems, you can use arecord's raw mode and pipe it to Watson STT through the websocket API.

**Comment by GuiJordao21** [comment]
Was anyone able to do this?? I'm trying my best here, but it's a bit tricky.

**Comment by aishaambar** [comment]
I'm still working on it. After necessary modifications, script has some logical errors but it's working.

**Comment by aishaambar** [comment]
@philippe-gregoire yes  I'm using PyAudio

**Comment by GuiJordao21** [comment]
@aishaambar Can you share your code with us?
