### ISSUE TITLE
I have a problem with TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by HayongLee** [watson-developer-cloud/speech-to-text-websockets-python#23]
I've got this error at line 350

auth = args.credentials[0] + ":" + args.credentials[1]
headers["Authorization"] = "Basic " + base64.b64encode(auth)

how should I solve it?
<img width="788" alt="2017-10-05 12 39 29" src="https://user-images.githubusercontent.com/26716042/31184930-ae875a54-a965-11e7-8bcd-714e1a2b6e69.png">

**Comment by GuiJordao21** [comment]
same problem here. I have no ideia what i could do

**Comment by albertobeto** [comment]
I replaced the line with:
        headers["Authorization"] = "Basic " + base64.b64encode(auth.encode()).decode()
