### ISSUE TITLE
Undefined name 'status' in sttClient.py

### ISSUE THREAD

**Issue by cclauss** [watson-developer-cloud/speech-to-text-websockets-python#27]
Should this be __value['status']__ instead?

[flake8](http://flake8.pycqa.org) testing of https://github.com/watson-developer-cloud/speech-to-text-websockets-python on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./sttClient.py:401:37: F821 undefined name 'status'
            print(fmt.format(key, **status))
                                    ^
1     F821 undefined name 'status'
1
```

**Comment by daniel-bolanos** [comment]
hi @cclauss I'm not sure this tool is meant to work on python 3.7.1. When I originally wrote it I targeted python 2.7.

**Comment by cclauss** [comment]
__flake8__ returns the same result when run on Python 2.7.  In a compiled language this issue would be caught by the compiler at compile time but more dynamic languages like Python have fewer checks so linting with tools like flake8 is more important.  Look at the code and think like a compiler. Try to determine what is the value of __status__ just before this line is run.  I believe that you will discover that __status__ was never defined.
