### ISSUE TITLE
is there a limit around 20 minutes?

### ISSUE THREAD

**Issue by berio** [watson-developer-cloud/speech-to-text-websockets-python#7]
Hi,
first of all, thank you for your script. It really helped me a lot.
I noticed that when I try to transcribe a large file, like for example one of 60 minutes, it stops transcribing around minute 22-23. I tried using several audio files, and it always finishes around that time. 
Is there any time constraints or some configuration that I am missing?
Are you aware of this limitation?

Thank you very much

**Comment by nfriedly** [comment]
There's a limit of 100mb, that could be the issue. Is it feasible to break your audio into smaller chunks? (And/or compress it with FLAC or Opus?)

**Comment by berio** [comment]
Ok, my audio is around 150 MB. That could be the issue then.
I'll try to compress it.
Thank you very much!

**Comment by daniel-bolanos** [comment]
Hi, I'm glad you are finding the script helpful. Yes, if the file is large then it is better to compress it so you do not run into the 100MB limitation. With opus or flac you can get 10x or 5x compression.

Dani
